name: eds_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  chalk: ^1.2.1
  chalkdart: ^2.0.9
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  enefty_icons: ^1.0.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
